<a href="https://colab.research.google.com/github/abhavasal/ProgrammingAssignment2/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
import tensorflow as tf

1st code to create an artificial neural network

In [23]:
tf.__version__

'2.4.1'

In [24]:
dataset= pd.read_csv("Churn_Modelling.csv")
x=dataset.iloc[:,3:-1].values
y = dataset.iloc[:, -1].values

In [25]:
dataset.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [27]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [28]:
#one hot encoding for geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [29]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [31]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [32]:
ann=tf.keras.models.Sequential()

In [33]:
#add input and hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [34]:
#adding one more hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [35]:
#adding outputlayer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [36]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [37]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5741 - accuracy: 0.7348
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4925 - accuracy: 0.7934
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4549 - accuracy: 0.8042
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4498 - accuracy: 0.8045
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4329 - accuracy: 0.8124
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4216 - accuracy: 0.8153
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4081 - accuracy: 0.8275
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3998 - accuracy: 0.8270
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4044 - accuracy: 0.8224
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3949 - accura

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

In [41]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)


[[False]]


In [43]:
y_pred= ann.predict(x_test)
y_pred =(y_pred >0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[1522   73]
 [ 208  197]]


0.8595